package com.iua.agustinpereyra.utils

const val USERNAME = "USERNAME"
const val VIEW_USER_REQUEST = 1
const val STATE_USERNAME = "STATE_USERNAME"
const val STATE_PASSWORD = "STATE_PASSWORD"
const val STATE_PASSWORD_OLD = STATE_PASSWORD
const val STATE_PASSWORD_NEW = "STATE_PASSWORD_NEW"
const val STATE_PASSWORD_VALIDATE = "STATE_PASSWORD_VALIDATE"
const val STATE_EMAIL = "STATE_EMAIL"